Repository libcpr/cpr, pull requests merged in 2020-06, with the labels that each got.

#390 Fix build after 7e4a803
  include/cpr/curlholder.h
Labels: Bug, Build

#397 Move Find_Package operations to root, Fixes #395
  CMakeLists.txt
  cmake/code_coverage.cmake
  cmake/mongoose.CMakeLists.txt
  opt/CMakeLists.txt
Labels: Bug, Build

#399 Fix install target for cpr (Fixes #398)
  cpr/CMakeLists.txt
Labels: Bug, Build

#401 Fix docs for #383
  index.md
Labels: Documentation

#402 Pass correct data type when setting CURLOPT_POSTFIELDSIZE_LARGE
  cpr/session.cpp
Labels: Bug

#411 Allow implicit creation of URL objects
  include/cpr/body.h
  include/cpr/cprtypes.h
  include/cpr/user_agent.h
Labels: Feature
