Repository libcpr/cpr, pull requests merged in 2020-05, with the labels that each got.

#380 Add move constructor and assignment to Session
  cpr/session.cpp
  include/cpr/session.h
Labels: Feature

#276 add SSL options
  cpr/CMakeLists.txt
  cpr/session.cpp
  cpr/ssl_options.cpp
  gen-test-key.sh
  include/cpr/session.h
  include/cpr/ssl_options.h
  include/cpr/verbose.h
  opt/CMakeLists.txt
  test/CMakeLists.txt
  test/data/10c14023.0
  test/data/10c14023.1
  test/data/88d0bdcb.0
  test/data/ca.crt
  test/data/ca.key
  test/data/ca.srl
  test/data/cert.csr
  test/data/cert.pem
  test/data/key.pem
  test/data/server.pem
  test/error_tests.cpp
  test/server.cpp
  test/server.h
  test/ssl_tests.cpp
Labels: Documentation Needed, Feature

#386 export upload size and download size in response
  cpr/session.cpp
  include/cpr/response.h
Labels: Feature

#384 Document NTLM auth
  introduction.md
Labels: Documentation
