Repository libcpr/cpr, pull requests merged in 2020-08, with the labels that each got.

#435 Only set client cert/key in libcurl when a value is set.
  cpr/session.cpp
Labels: Bug :bug:

#441 Fix: typo in curlholder.cpp
  cpr/curlholder.cpp
Labels: Enhancement :ok_hand:

#440 Change external projects download method to https
  CMakeLists.txt
Labels: Build :construction_worker:, Enhancement :ok_hand:
