Repository libcpr/cpr, pull requests merged in 2020-10, with the labels that each got.

#429 Added support for sanitizers (CLoses #419)
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/sanitizer.cmake
  cpr/curlholder.cpp
Labels: Build :construction_worker:, Feature :sparkles:

#452 Fixed AbstractServer data race
  test/abstractServer.hpp
Labels: Enhancement :ok_hand:

#453 Added support for retrieving certificate information [Closes #444]
  cpr/CMakeLists.txt
  cpr/response.cpp
  cpr/session.cpp
  include/cpr/response.h
  test/ssl_tests.cpp
Labels: Feature :sparkles:

#454 Documentation for #453
  advanced-usage.md
Labels: Documentation :books:
