Repository libcpr/cpr, pull requests merged in 2020-07, with the labels that each got.

#415 Provide hashes for git content to replace the security of submodules
  CMakeLists.txt
  README.md
Labels: Build, Feature

#416 Add Conan package manager usage example
  README.md
Labels: Documentation

#404 CMake add ability to use WINSSL
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/mongoose.CMakeLists.txt
  cpr/CMakeLists.txt
  test/CMakeLists.txt
  test/ssl_tests.cpp
Labels: Build, Feature

#426 Add missing Session methods
  cpr/session.cpp
Labels: Bug

#427 Add Required flag to threads
  test/CMakeLists.txt
Labels: Bug

#425 Simplify Authentication classes and make them copyable/movable
  cpr/CMakeLists.txt
  cpr/digest.cpp
  cpr/ntlm.cpp
  include/cpr/auth.h
  include/cpr/digest.h
  include/cpr/ntlm.h
Labels: Feature

#428 fix: Don't search for invalid cURL components
  CMakeLists.txt
Labels: Bug, Build
