Repository libcpr/cpr, pull requests merged in 2020-04, with the labels that each got.

#349 Add vcpkg installation instructions
  README.md
Labels: Feature

#363 Download to filestream
  cpr/session.cpp
  cpr/util.cpp
  include/cpr/api.h
  include/cpr/session.h
  include/cpr/util.h
Labels: Feature

#283 Feature/download
  cpr/session.cpp
  cpr/util.cpp
  include/cpr/api.h
  include/cpr/session.h
  include/cpr/util.h
Labels: Tests Needed

#339 Add background-color to website
  stylesheets/styles.css
Labels: Bug

#334 Add option to Rate Limit session
  cpr/CMakeLists.txt
  cpr/session.cpp
  include/cpr/limit_rate.h
  include/cpr/session.h
Labels: Feature

#251 make the response object return more info about headers
  cpr/session.cpp
  cpr/util.cpp
  include/cpr/response.h
  include/cpr/util.h
  test/util_tests.cpp
Labels: Feature

#340 Add version information for shared libraries.
  CMakeLists.txt
  cpr/CMakeLists.txt
Labels: Build, Feature

#365 Add ability to iterate over Cookies
  cpr/cookies.cpp
  include/cpr/cookies.h
Labels: Feature

#366 Have libcurl request all compression encodings it can handle.
  cpr/session.cpp
Labels: Feature

#282 Add unix socket support
  cpr/CMakeLists.txt
  cpr/session.cpp
  cpr/unix_socket.cpp
  include/cpr/session.h
  include/cpr/unix_socket.h
Labels: Awaiting Resonse, Feature

#370 Added an option to disable cookie encoding #369
  cpr/cookies.cpp
  include/cpr/cookies.h
Labels: Documentation Needed, Feature
