Repository libcpr/cpr, pull requests merged in 2021-08, with the labels that each got.

#601 add userdata param to callback function
  cpr/util.cpp
  include/cpr/callback.h
  test/callback_tests.cpp
Labels: Feature :sparkles:

#600 add userdata parameter to callback function
  advanced-usage.md
Labels: Documentation :books:

#604 add document for Download
  advanced-usage.md
Labels: Documentation :books:

#599 add interface GetDownloadFileLength
  cpr/session.cpp
  include/cpr/session.h
Labels: Feature :sparkles:

#614 Fixed #613
  cpr/session.cpp
Labels: Bug :bug:

#616 CURLOPT_INTERFACE -> SetInterface(...)
  cpr/session.cpp
  include/CMakeLists.txt
  include/cpr/cpr.h
  include/cpr/interface.h
  include/cpr/session.h
  test/get_tests.cpp
Labels: Feature :sparkles:

#618 Custom interface docu
  advanced-usage.md
Labels: Documentation :books:

#617 Respect system proxy configurations
  cpr/session.cpp
Labels: Bug :bug:

#621 Docs for #620
  advanced-usage.md
Labels: Documentation :books:
