Repository libcpr/cpr, pull requests merged in 2022-12, with the labels that each got.

#855 Fixed GetDownloadFileLength error
  cpr/session.cpp
  test/download_tests.cpp
  test/httpServer.cpp
  test/httpServer.hpp
Labels: Bug :bug:

#857 API type tweaks
  CppCheckSuppressions.txt
  include/cpr/auth.h
  include/cpr/bearer.h
  include/cpr/body.h
  include/cpr/cprtypes.h
  include/cpr/curl_container.h
  include/cpr/file.h
  include/cpr/interface.h
  include/cpr/proxyauth.h
  include/cpr/unix_socket.h
  include/cpr/user_agent.h
Labels: Enhancement :ok_hand:

#863 Mutiperform Intercept
  cpr/interceptor.cpp
  cpr/multiperform.cpp
  cpr/session.cpp
  include/cpr/interceptor.h
  include/cpr/multiperform.h
  include/cpr/session.h
  test/CMakeLists.txt
  test/interceptor_multi_tests.cpp
  test/interceptor_tests.cpp
Labels: Feature :sparkles:
