Repository libcpr/cpr, pull requests merged in 2022-08, with the labels that each got.

#798 Disable the header "Expect: 100-continue" by default (#293)
  cpr/session.cpp
  test/httpServer.cpp
  test/httpServer.hpp
  test/session_tests.cpp
Labels: Enhancement :ok_hand:

#789 NuGet package
  .github/workflows/build-nuget.yml
  .gitignore
  README.md
  nuget/build/native/libcpr.props
  nuget/build/native/libcpr.targets
  nuget/libcpr.nuspec
  nuget/resources/cpr.png
Labels: Feature :sparkles:, Build :construction_worker:

#801 iOS support
  .gitignore
  CMakeLists.txt
  include/cpr/body.h
Labels: Enhancement :ok_hand:

#802 Fixed thread pool not creating enough new threads
  cpr/threadpool.cpp
  include/cpr/async.h
  include/cpr/threadpool.h
Labels: Bug :bug:

#774 Mongoose update
  CMakeLists.txt
  cmake/mongoose.CMakeLists.txt
  test/CMakeLists.txt
  test/abstractServer.cpp
  test/abstractServer.hpp
  test/callback_tests.cpp
  test/error_tests.cpp
  test/httpServer.cpp
  test/httpServer.hpp
  test/httpsServer.cpp
  test/httpsServer.hpp
  test/multiperform_tests.cpp
  test/session_tests.cpp
  test/ssl_tests.cpp
Labels: Enhancement :ok_hand:

#806 📝 add documentation to CMake find-package support
  README.md
Labels: Documentation :books:, Enhancement :ok_hand:

#803 Fix iOS check for skipping CA bundle search
  CMakeLists.txt
Labels: Bug :bug:, Build :construction_worker:

#810 Add CURL_VERBOSE_LOGGING option to enable debug features during curl …
  CMakeLists.txt
Labels: Feature :sparkles:, Build :construction_worker:

#814 Add std::map based constructors to Proxies and ProxyAuthentication
  cpr/proxies.cpp
  include/cpr/proxies.h
  include/cpr/proxyauth.h
Labels: Enhancement :ok_hand:

#816 Remove redundant const qualification in auth.h
  include/cpr/auth.h
Labels: Enhancement :ok_hand:
