Repository libcpr/cpr, pull requests merged in 2022-09, with the labels that each got.

#820 Support manual hostname resolution
  cpr/curlholder.cpp
  cpr/session.cpp
  include/CMakeLists.txt
  include/cpr/cpr.h
  include/cpr/curlholder.h
  include/cpr/resolve.h
  include/cpr/session.h
  test/CMakeLists.txt
  test/abstractServer.cpp
  test/abstractServer.hpp
  test/httpServer.cpp
  test/httpServer.hpp
  test/resolve_tests.cpp
Labels: Feature :sparkles:, Documentation Needed :green_book:

#821 File loading cleanup
  include/cpr/body.h
Labels: Enhancement :ok_hand:

#812 Compatiblity for OSX without filesystem.h
  .github/workflows/ci.yml
  CMakeLists.txt
  include/CMakeLists.txt
  include/cpr/api.h
  include/cpr/filesystem.h
Labels: Bug :bug:
