Repository libcpr/cpr, pull requests merged in 2022-05, with the labels that each got.

#736 clang-format CI and CI cleanup
  .github/workflows/ci.yml
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy.yml
  .github/workflows/cppcheck.yml
  cpr/cprtypes.cpp
  cpr/curl_container.cpp
  cpr/proxies.cpp
  cpr/response.cpp
  cpr/util.cpp
  include/cpr/api.h
  include/cpr/auth.h
  include/cpr/bearer.h
  include/cpr/cookies.h
  include/cpr/curl_container.h
  include/cpr/digest.h
  include/cpr/limit_rate.h
  include/cpr/multipart.h
  include/cpr/ntlm.h
  include/cpr/range.h
  include/cpr/reserve_size.h
  include/cpr/ssl_options.h
  include/cpr/util.h
  test/abstractServer.hpp
  test/async_tests.cpp
  test/delete_tests.cpp
  test/error_tests.cpp
  test/httpServer.cpp
  test/httpsServer.cpp
  test/httpsServer.hpp
  test/options_tests.cpp
  test/prepare_tests.cpp
  test/raw_body_tests.cpp
  test/ssl_tests.cpp
  test/structures_tests.cpp
Labels: Feature :sparkles:, CI :bricks:, Enhancement :ok_hand:

#739 Running clang-{tidy, format} and cppcheck for PRs
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy.yml
  .github/workflows/cppcheck.yml
Labels: CI :bricks:, Enhancement :ok_hand:

#735 Unified basic, digest and ntlm authentication into one authenticaton class
  README.md
  cpr/auth.cpp
  cpr/session.cpp
  include/CMakeLists.txt
  include/cpr/api.h
  include/cpr/auth.h
  include/cpr/cpr.h
  include/cpr/digest.h
  include/cpr/ntlm.h
  include/cpr/session.h
  test/get_tests.cpp
  test/head_tests.cpp
  test/session_tests.cpp
Labels: Enhancement :ok_hand:, Breaking Change 🔥

#738 Use UpdateHeader to allow header updates from different sources
  include/cpr/api.h
  test/post_tests.cpp
Labels: Documentation Needed :green_book:, Enhancement :ok_hand:

#741 Added function to get the full request URL
  cpr/session.cpp
  include/cpr/session.h
  test/session_tests.cpp
Labels: Feature :sparkles:

#734 Use thread pool to instead of std::async (#633)
  cpr/CMakeLists.txt
  cpr/async.cpp
  cpr/threadpool.cpp
  include/CMakeLists.txt
  include/cpr/api.h
  include/cpr/async.h
  include/cpr/singleton.h
  include/cpr/threadpool.h
Labels: Feature :sparkles:

#744 Add Interceptors
  cpr/CMakeLists.txt
  cpr/interceptor.cpp
  cpr/session.cpp
  include/CMakeLists.txt
  include/cpr/cpr.h
  include/cpr/interceptor.h
  include/cpr/session.h
  test/CMakeLists.txt
  test/interceptor_tests.cpp
Labels: Feature :sparkles:, Breaking Change 🔥

#748 Support for CURLOPT_LOCALPORT and CURLOPT_LOCALPORTRANGE
  cpr/session.cpp
  include/CMakeLists.txt
  include/cpr/cpr.h
  include/cpr/local_port.h
  include/cpr/local_port_range.h
  include/cpr/session.h
  test/httpServer.cpp
  test/httpServer.hpp
  test/session_tests.cpp
Labels: Tests Needed :rotating_light:, Feature :sparkles:, Documentation Needed :green_book:
