Repository libcpr/cpr, pull requests merged in 2022-11, with the labels that each got.

#848 Added a default cpr::Session move ctr
  include/cpr/session.h
Labels: Enhancement :ok_hand:

#846 Add instructions for building with Bazel
  README.md
Labels: Documentation :books:, Build :construction_worker:, Enhancement :ok_hand:

#853 Disable adding configurations.
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/sanitizer.cmake
Labels: Bug :bug:, Build :construction_worker:
