Repository libcpr/cpr, pull requests merged in 2022-03, with the labels that each got.

#707 Fix for certificate verification on android
  CMakeLists.txt
Labels: Bug :bug:, curl :globe_with_meridians:

#713 Updated The CMake generator for Windows CI runs
  .github/workflows/ci.yml
Labels: CI :bricks:

#714 Mbed TLS support
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/FindMbedTLS.cmake
Labels: Feature :sparkles:

#717 Fix overwriting of ca bundle
  CMakeLists.txt
Labels: Bug :bug:, curl :globe_with_meridians:
