Repository libcpr/cpr, pull requests merged in 2022-07, with the labels that each got.

#776 Securely remove sensitive data from memory
  cpr/auth.cpp
  cpr/bearer.cpp
  cpr/proxyauth.cpp
  cpr/util.cpp
  include/cpr/auth.h
  include/cpr/bearer.h
  include/cpr/proxyauth.h
  include/cpr/ssl_options.h
  include/cpr/util.h
Labels: Bug :bug:

#779 `secureStringClear` Fix for Empty Strings
  cpr/util.cpp
  test/util_tests.cpp
Labels: Bug :bug:, Enhancement :ok_hand:

#773 New certificates for HTTPS tests
  test/CMakeLists.txt
  test/data/ca.cer
  test/data/ca.key
  test/data/certificates/client.crt
  test/data/certificates/root-ca.crt
  test/data/certificates/server.crt
  test/data/client.cer
  test/data/client.cnf
  test/data/client.key
  test/data/generate-certificates.sh
  test/data/generate.sh
  test/data/keys/client.key
  test/data/keys/root-ca.key
  test/data/keys/server.key
  test/data/keys/server.pub
  test/data/root-ca.cnf
  test/data/server.cer
  test/data/server.cnf
  test/data/server.key
  test/data/server.pubkey
  test/ssl_tests.cpp
Labels: Bug :bug:

#783 MacOS and Windows OpenSSL CI fixes
  .github/workflows/ci.yml
  CMakeLists.txt
  cpr/CMakeLists.txt
  test/CMakeLists.txt
  test/session_tests.cpp
Labels: CI :bricks:, dependencies

#784 Fixed #780 - Ubuntu 16 not supported any more - explicit_bzero
  .clang-tidy
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy.yml
  cpr/async.cpp
  cpr/curlholder.cpp
  cpr/session.cpp
  cpr/util.cpp
  include/cpr/util.h
Labels: Bug :bug:

#778 Refactor cpr::Cookies for storing more fields (#777)
  cpr/cookies.cpp
  cpr/util.cpp
  include/cpr/cookies.h
  include/cpr/util.h
  test/get_tests.cpp
  test/head_tests.cpp
  test/httpServer.cpp
  test/httpServer.hpp
  test/post_tests.cpp
  test/prepare_tests.cpp
  test/session_tests.cpp
  test/util_tests.cpp
Labels: Feature :sparkles:, Documentation Needed :green_book:, Breaking Change 🔥

#781 Fix certificate information extraction from the response (#769)
  cpr/CMakeLists.txt
  cpr/cert_info.cpp
  cpr/response.cpp
  include/CMakeLists.txt
  include/cpr/cert_info.h
  include/cpr/cpr.h
  include/cpr/response.h
  test/ssl_tests.cpp
Labels: Documentation Needed :green_book:, Enhancement :ok_hand:, Breaking Change 🔥

#787 Workaround for PUT requests with a read callback
  cpr/session.cpp
  test/callback_tests.cpp
Labels: Bug :bug:

#793 Add support of uploading multiple files within the same multipart field (#563)
  cpr/CMakeLists.txt
  cpr/file.cpp
  cpr/session.cpp
  include/cpr/file.h
  include/cpr/multipart.h
  test/httpServer.cpp
  test/post_tests.cpp
  test/session_tests.cpp
Labels: Feature :sparkles:

#770 Implement curl_multi_perform
  cpr/CMakeLists.txt
  cpr/curlmultiholder.cpp
  cpr/multiperform.cpp
  cpr/session.cpp
  include/CMakeLists.txt
  include/cpr/api.h
  include/cpr/cpr.h
  include/cpr/curlmultiholder.h
  include/cpr/multiperform.h
  include/cpr/response.h
  include/cpr/session.h
  test/CMakeLists.txt
  test/multiperform_tests.cpp
Labels: Feature :sparkles:
