Repository libcpr/cpr, pull requests merged in 2022-06, with the labels that each got.

#750 Add CaBuffer to enable loading of CA certificates from buffers
  CMakeLists.txt
  cpr/CMakeLists.txt
  cpr/session.cpp
  cpr/ssl_ctx.cpp
  include/CMakeLists.txt
  include/cpr/cpr.h
  include/cpr/ssl_ctx.h
  include/cpr/ssl_options.h
  test/CMakeLists.txt
  test/ssl_tests.cpp
Labels: Feature :sparkles:

#746 Add method SetAcceptEncoding for customized Accept-Encoding header (#683)
  cpr/CMakeLists.txt
  cpr/accept_encoding.cpp
  cpr/session.cpp
  include/CMakeLists.txt
  include/cpr/accept_encoding.h
  include/cpr/session.h
  test/httpServer.cpp
  test/httpServer.hpp
  test/session_tests.cpp
Labels: Feature :sparkles:, Documentation Needed :green_book:

#755 Add support of customized filename for Multipart (#642)
  cpr/session.cpp
  include/cpr/multipart.h
  test/httpServer.cpp
  test/post_tests.cpp
Labels: Enhancement :ok_hand:

#760 Added CI script for automatically building a debian package
  .github/workflows/build-deb.yml
  package-build/build-package.sh
  package-build/debian-libcpr/README.Debian
  package-build/debian-libcpr/changelog
  package-build/debian-libcpr/control
  package-build/debian-libcpr/copyright
  package-build/debian-libcpr/rules
Labels: Build :construction_worker:, CI :bricks:

#764 Add unit tests for file uploading using buffer of rvalue/lvalue reference (#216)
  test/post_tests.cpp
Labels: Enhancement :ok_hand:

#756 Add async methods to the Session object interface
  cpr/session.cpp
  include/cpr/session.h
  test/session_tests.cpp
Labels: Feature :sparkles:, Documentation Needed :green_book:

#763 Add support of file and buffer for the POST Body (#581)
  include/CMakeLists.txt
  include/cpr/body.h
  include/cpr/buffer.h
  include/cpr/file.h
  include/cpr/multipart.h
  test/post_tests.cpp
Labels: Enhancement :ok_hand:
