Repository libcpr/cpr, pull requests merged in 2023-12, with the labels that each got.

#992 GitHub action for auto-updating GIT_TAG in readme
  .github/workflows/readme-updater.yml
  README.md
Labels: Feature :sparkles:, CI :bricks:

#998 clang-tidy fixes
  cpr/accept_encoding.cpp
  cpr/bearer.cpp
  cpr/callback.cpp
  cpr/cert_info.cpp
  cpr/cookies.cpp
  cpr/cprtypes.cpp
  cpr/curl_container.cpp
  cpr/curlholder.cpp
  cpr/curlmultiholder.cpp
  cpr/error.cpp
  cpr/file.cpp
  cpr/interceptor.cpp
  cpr/multipart.cpp
  cpr/multiperform.cpp
  cpr/parameters.cpp
  cpr/payload.cpp
  cpr/proxyauth.cpp
  cpr/redirect.cpp
  cpr/response.cpp
  cpr/session.cpp
  cpr/ssl_ctx.cpp
  cpr/threadpool.cpp
  cpr/timeout.cpp
  cpr/util.cpp
  include/cpr/api.h
  include/cpr/curlholder.h
  include/cpr/multiperform.h
  test/callback_tests.cpp
  test/multiasync_tests.cpp
  test/ssl_tests.cpp
Labels: Bug :bug:, Build :construction_worker:

#1000 Fixes #932 - `CURL_PROGRESSFUNC_CONTINUE` not always defined
  include/cpr/util.h
Labels: Bug :bug:

#1002 Fixed openssl/types.h include for ubuntu20.04
  cpr/ssl_ctx.cpp
Labels: Bug :bug:

#1004 Reverted to actions/checkout@v3 to deal with old node versions
  .github/workflows/build-deb.yml
  .github/workflows/build-nuget.yml
  .github/workflows/ci.yml
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy.yml
  .github/workflows/cppcheck.yml
  .github/workflows/readme-updater.yml
Labels: Bug :bug:, CI :bricks:
