Repository libcpr/cpr, pull requests merged in 2023-08, with the labels that each got.

#934 Avoid conflicts with external components
  include/cpr/filesystem.h
Labels: Enhancement :ok_hand:

#923 Add vector<Part> param to Multipart initialization
  cpr/multipart.cpp
  include/cpr/multipart.h
  test/session_tests.cpp
Labels: Enhancement :ok_hand:

#887 ndk stdc++fs library error
  include/CMakeLists.txt
Labels: Bug :bug:, Build :construction_worker:

#935 Using Test Matrix for Validating all Combinations
  .clang-tidy
  .github/workflows/ci.yml
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cppcheck.yml
  test/callback_tests.cpp
  test/error_tests.cpp
  test/session_tests.cpp
Labels: CI :bricks:, Enhancement :ok_hand:

#937 Fix/clang windows warnings #927
  CMakeLists.txt
  cpr/curl_container.cpp
  cpr/curlmultiholder.cpp
  cpr/interceptor.cpp
  cpr/multiperform.cpp
  cpr/parameters.cpp
  cpr/payload.cpp
  cpr/response.cpp
  cpr/session.cpp
  cpr/ssl_ctx.cpp
  cpr/util.cpp
  include/CMakeLists.txt
  include/cpr/cert_info.h
  include/cpr/cookies.h
  include/cpr/curlmultiholder.h
  include/cpr/file.h
  include/cpr/interceptor.h
  include/cpr/limit_rate.h
  include/cpr/local_port.h
  include/cpr/local_port_range.h
  include/cpr/multiperform.h
  include/cpr/parameters.h
  include/cpr/payload.h
  include/cpr/redirect.h
  include/cpr/ssl_ctx.h
  include/cpr/ssl_options.h
  include/cpr/status_codes.h
  test/get_tests.cpp
  test/head_tests.cpp
Labels: Bug :bug:, Build :construction_worker:, Windows :tv:

#945 Update zlib-ng and gtest to circumvent curl missing the zlib target
  CMakeLists.txt
  cmake/zlib_external.cmake
Labels: Bug :bug:, Build :construction_worker:

#948 Not linking against stdc++fs on WIN32
  .clang-tidy
  include/CMakeLists.txt
Labels: Bug :bug:, Build :construction_worker:, Windows :tv:

#949 Fixed CI triggers for PRs
  .github/workflows/build-deb.yml
  .github/workflows/ci.yml
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy.yml
  .github/workflows/cppcheck.yml
Labels: Bug :bug:, CI :bricks:

#952 CMake Proxy Test Options - 1.9.x
  CMakeLists.txt
  test/CMakeLists.txt
Labels: Enhancement :ok_hand:

#951 Clang tidy fixes
  cpr/cookies.cpp
  cpr/curl_container.cpp
  cpr/redirect.cpp
  cpr/session.cpp
  cpr/ssl_ctx.cpp
  cpr/threadpool.cpp
  cpr/util.cpp
Labels: Build :construction_worker:, Enhancement :ok_hand:

#950 Fix cpr Include Statements - Backported #946
  test/alternating_tests.cpp
  test/async_tests.cpp
  test/callback_tests.cpp
  test/delete_tests.cpp
  test/download_tests.cpp
  test/encoded_auth_tests.cpp
  test/error_tests.cpp
  test/head_tests.cpp
  test/options_tests.cpp
  test/patch_tests.cpp
  test/post_tests.cpp
  test/prepare_tests.cpp
  test/proxy_tests.cpp
  test/put_tests.cpp
  test/raw_body_tests.cpp
  test/session_tests.cpp
  test/ssl_tests.cpp
  test/structures_tests.cpp
  test/util_tests.cpp
  test/version_tests.cpp
Labels: Bug :bug:
