Repository libcpr/cpr, pull requests merged in 2023-01, with the labels that each got.

#867 build in -> built-in
  CMakeLists.txt
Labels: Build :construction_worker:, Enhancement :ok_hand:

#868 Fixed thread pool not creating enough new threads after awhile
  cpr/threadpool.cpp
Labels: Bug :bug:

#873 Disable HTTP_ONLY option
  CMakeLists.txt
Labels: Feature :sparkles:, Build :construction_worker:

#874 Add check for CMP0135
  CMakeLists.txt
Labels: Build :construction_worker:, Enhancement :ok_hand:

#864 MultiAsync
  .gitignore
  cpr/CMakeLists.txt
  cpr/callback.cpp
  cpr/session.cpp
  cpr/util.cpp
  include/CMakeLists.txt
  include/cpr/api.h
  include/cpr/async.h
  include/cpr/async_wrapper.h
  include/cpr/callback.h
  include/cpr/cprtypes.h
  include/cpr/session.h
  include/cpr/util.h
  test/CMakeLists.txt
  test/multiasync_tests.cpp
  test/multiasync_tests.hpp
Labels: Feature :sparkles:
