Repository libcpr/cpr, pull requests merged in 2023-09, with the labels that each got.

#955 Unencoded Cookies Test
  test/get_tests.cpp
Labels: Feature :sparkles:

#962 Fix dangling reference to callback after move
  cpr/session.cpp
  include/cpr/session.h
  test/session_tests.cpp
Labels: Bug :bug:

#965 Docs for how to execute tests
  README.md
Labels: Documentation :books:, Enhancement :ok_hand:
