Repository libcpr/cpr, pull requests merged in 2023-03, with the labels that each got.

#877 Improvements to CPR_USE_BOOST_FILESYSTEM
  .github/workflows/ci.yml
  CMakeLists.txt
  include/cpr/api.h
  include/cpr/filesystem.h
Labels: Build :construction_worker:, Enhancement :ok_hand:

#880 Fix version
  CMakeLists.txt
Labels: Bug :bug:, Build :construction_worker:

#875 proxy authentication fix
  cpr/proxyauth.cpp
  cpr/session.cpp
  include/cpr/proxyauth.h
  test/encoded_auth_tests.cpp
Labels: Bug :bug:

#890 Curl formfree deprecation
  cpr/curlholder.cpp
  cpr/session.cpp
  include/cpr/buffer.h
  include/cpr/curlholder.h
  include/cpr/multipart.h
  include/cpr/ssl_options.h
  test/ssl_tests.cpp
Labels: curl :globe_with_meridians:, Enhancement :ok_hand:

#889 Potential SSL Windows no revoke fix
  cpr/session.cpp
Labels: Bug :bug:, Windows :tv:

#893 fix error: using typedef-name ‘curl_mime’ after ‘struct’ (#892)
  include/cpr/curlholder.h
Labels: Bug :bug:
