Repository libcpr/cpr, pull requests merged in 2024-05, with the labels that each got.

#936 Added Unit Tests for Special File Names
  cpr/session.cpp
  test/CMakeLists.txt
  test/data/test_file.txt
  test/data/test_file_hello_äüöp_2585.txt
  test/data/test_file_hello_äüöp_2585_你好.txt
  test/file_upload_tests.cpp
  test/httpServer.cpp
  test/httpServer.hpp
  test/ssl_tests.cpp
Labels: Enhancement :ok_hand:

#1052 Fixed std::filesystem::path to C-string Conversion On Windows
  cpr/session.cpp
Labels: Bug :bug:, Windows :tv:

#1009 WIP macOS CI Fixes
  .github/workflows/ci.yml
  cmake/mongoose.CMakeLists.txt
Labels: Bug :bug:, CI :bricks:

#1055 fix: fallback from curl_multi_poll to curl_multi_wait before curl 7.66
  cpr/multiperform.cpp
Labels: Enhancement :ok_hand:
