Repository libcpr/cpr, pull requests merged in 2024-12, with the labels that each got.

#1154 Replace ubuntu:22.04 and ubuntu:23.04 with ubuntu:latest
  .github/workflows/ci.yml
Labels: Bug :bug:, CI :bricks:

#1151 [BUG] Fix cpr::ssl:KeyBlob: Copy blob to curl
  cpr/session.cpp
  test/ssl_tests.cpp
Labels: Bug :bug:

#1125 Added handling no_proxy override through Proxies
  cpr/session.cpp
  test/proxy_tests.cpp
Labels: Feature :sparkles:, Documentation Needed :green_book:
