Repository libcpr/cpr, pull requests merged in 2024-11, with the labels that each got.

#1128 Resolve CURLOPT_SSL_OPTIONS issues
  cpr/session.cpp
Labels: Bug :bug:

#1139 fix: remove duplicate call in `Session::prepareCommonDownload()`
  cpr/session.cpp
Labels: Bug :bug:

#1144 Update To The Latest Clang-Tidy Version
  .clang-tidy
  cpr/cookies.cpp
  cpr/multiperform.cpp
  cpr/ssl_ctx.cpp
  cpr/threadpool.cpp
Labels: Build :construction_worker:, Enhancement :ok_hand:

#1142 `Enhance`: Use unordered_map for CURL error mapping
  cpr/error.cpp
  include/cpr/error.h
Labels: Enhancement :ok_hand:

#1148 Public cpr::Session::GetSharedPtrFromThis
  include/cpr/session.h
Labels: Bug :bug:
