Repository libcpr/cpr, pull requests merged in 2024-10, with the labels that each got.

#1120 Curl Minimum Supported Version 7.64.0
  CMakeLists.txt
  README.md
  cpr/CMakeLists.txt
  cpr/error.cpp
  test/CMakeLists.txt
Labels: Bug :bug:, Feature :sparkles:

#1115 Preperation For 1.11.0 Release
  .github/workflows/ci.yml
  cpr/error.cpp
Labels: Feature :sparkles:

#1116 Preperation For 1.9.8 Release
  .clang-tidy
  .github/workflows/build-deb.yml
  .github/workflows/ci.yml
  .github/workflows/clang-format.yml
  .gitignore
  .vscode/tasks.json
  CMakeLists.txt
  README.md
  cpr/CMakeLists.txt
  cpr/accept_encoding.cpp
  cpr/bearer.cpp
  cpr/cert_info.cpp
  cpr/cookies.cpp
  cpr/cprtypes.cpp
  cpr/curl_container.cpp
  cpr/curlholder.cpp
  cpr/error.cpp
  cpr/interceptor.cpp
  cpr/multipart.cpp
  cpr/parameters.cpp
  cpr/payload.cpp
  cpr/redirect.cpp
  cpr/response.cpp
  cpr/session.cpp
  cpr/ssl_ctx.cpp
  cpr/threadpool.cpp
  cpr/timeout.cpp
  cpr/util.cpp
  include/cpr/api.h
  include/cpr/body.h
  include/cpr/callback.h
  include/cpr/cprtypes.h
  include/cpr/error.h
  include/cpr/redirect.h
  include/cpr/response.h
  include/cpr/singleton.h
  include/cpr/util.h
  nuget/libcpr.nuspec
  scripts/check_clang_format.sh
  scripts/delete_build_dir.sh
  scripts/run_clang_format.sh
  test/CMakeLists.txt
  test/abstractServer.cpp
  test/async_tests.cpp
  test/callback_tests.cpp
  test/get_tests.cpp
Labels: Feature :sparkles:

#1123 Updated supported versions for 1.11.0
  README.md
Labels: Documentation :books:

#1132 `Fixed` grammatical issues and corrected spelling errors in README.md
  README.md
Labels: Documentation :books:, Enhancement :ok_hand:

#1131 `Refactored` timeout.h: added template ctr and removed redundant ctrs (#1129)
  include/cpr/timeout.h
Labels: Bug :bug:
