Repository libcpr/cpr, pull requests merged in 2024-07, with the labels that each got.

#1076 Const Response::GetCertInfos()
  cpr/response.cpp
  include/cpr/response.h
Labels: Enhancement :ok_hand:

#1078 add support for CURLAUTH_NEGOTIATE
  cpr/session.cpp
  include/cpr/auth.h
Labels: Feature :sparkles:

#1053 Removed Ubuntu 18.04 and added 24.04 CI runs
  .github/workflows/ci.yml
  include/cpr/threadpool.h
Labels: Feature :sparkles:, CI :bricks:

#1081 The header and write callback now uses a std::string_view as argument for data to avoid copying
  include/cpr/callback.h
  test/async_tests.cpp
  test/callback_tests.cpp
  test/download_tests.cpp
  test/interceptor_multi_tests.cpp
  test/interceptor_tests.cpp
  test/multiperform_tests.cpp
  test/session_tests.cpp
Labels: Enhancement :ok_hand:

#1067 Fix sensitive data leaking in Authentication
  cpr/auth.cpp
  include/cpr/auth.h
Labels: Enhancement :ok_hand:
