Repository libcpr/cpr, pull requests merged in 2025-04, with the labels that each got.

#1206 Refactor AsyncWrapper to make it safer
  include/cpr/async_wrapper.h
  test/multiasync_tests.cpp
Labels: Enhancement :ok_hand:

#1204 Do Not Check For Sanitizers If They Are Not Enabled
  CMakeLists.txt
  cmake/sanitizer.cmake
  test/multiasync_tests.cpp
Labels: Bug :bug:, Build :construction_worker:

#1211 Fix usage for TLS v1.3 cipher
  cpr/session.cpp
Labels: Bug :bug:

#1213 Better OpenSSL headers include based on headers version.
  .gitignore
  cpr/ssl_ctx.cpp
Labels: Bug :bug:
