Repository libcpr/cpr, pull requests merged in 2025-02, with the labels that each got.

#1170 Replaced the secureStringClear mechanism with a SecureString class
  cpr/CMakeLists.txt
  cpr/auth.cpp
  cpr/bearer.cpp
  cpr/cookies.cpp
  cpr/curl_container.cpp
  cpr/curlholder.cpp
  cpr/file.cpp
  cpr/proxyauth.cpp
  cpr/session.cpp
  cpr/util.cpp
  include/CMakeLists.txt
  include/cpr/auth.h
  include/cpr/bearer.h
  include/cpr/curlholder.h
  include/cpr/proxyauth.h
  include/cpr/secure_string.h
  include/cpr/ssl_options.h
  include/cpr/util.h
  test/util_tests.cpp
Labels: Feature :sparkles:

#1175 Clang-Tidy And cppcheck Fixes
  .clang-tidy
  .github/workflows/cppcheck.yml
  CppCheckSuppressions.txt
  cmake/cppcheck.cmake
  cppcheck-suppressions.xml
  cpr/cookies.cpp
  cpr/proxyauth.cpp
  cpr/session.cpp
  cpr/threadpool.cpp
  cpr/util.cpp
  include/cpr/cookies.h
  test/get_tests.cpp
Labels: Enhancement :ok_hand:

#1173 Getter function for Session::header_ to enable the user to read back all headers set and delete select ones
  CONTRIBUTING.md
  cpr/error.cpp
  cpr/session.cpp
  include/cpr/async_wrapper.h
  include/cpr/session.h
  include/cpr/timeout.h
  test/session_tests.cpp
Labels: Feature :sparkles:

#1182 Fix windows static library build parameter in CMakeLists.txt
  CMakeLists.txt
Labels: Feature :sparkles:, Build :construction_worker:, Windows :tv:

#1181 Fix Seg-fault when setting proxy username + password
  cpr/curlholder.cpp
  cpr/proxyauth.cpp
  cpr/session.cpp
  include/cpr/proxyauth.h
  include/cpr/session.h
  test/proxy_auth_tests.cpp
Labels: Bug :bug:

#1185 Cookie expires date is now only 100 days in the future
  test/get_tests.cpp
  test/head_tests.cpp
  test/httpServer.cpp
  test/httpServer.hpp
  test/session_tests.cpp
Labels: Bug :bug:, curl :globe_with_meridians:

#1187 add curl's ANY and ANSAFE authorization options
  cpr/session.cpp
  include/cpr/auth.h
  test/session_tests.cpp
Labels: Feature :sparkles:

#1188 Fixed memory leak in threadpool
  cpr/threadpool.cpp
  include/cpr/threadpool.h
Labels: Bug :bug:
