Repository libcpr/cpr, pull requests merged in 2025-03, with the labels that each got.

#1177 Add enforced HTTP/3
  cpr/session.cpp
  include/cpr/http_version.h
Labels: Feature :sparkles:

#1196 Update README.md to add Bazel extension instructions
  README.md
Labels: Documentation :books:, Feature :sparkles:

#1199 feat: Use CMAKE_MSVC_RUNTIME_LIBRARY for runtime selection in MSVC(#1…
  CMakeLists.txt
Labels: Bug :bug:, Build :construction_worker:, Windows :tv:

#1200 Update CMakeLists.txt project version for 1.11.2 release
  CMakeLists.txt
Labels: Bug :bug:

#1197 Add std::to_string functionality for ErrorCode to ease human meaningful logging
  cpr/proxyauth.cpp
  include/cpr/async_wrapper.h
  include/cpr/error.h
  include/cpr/session.h
  test/error_tests.cpp
Labels: Feature :sparkles:

#1205 Make cpr::async and HTTP (Get, Post, Put, etc.) callbacks cancelable
  include/cpr/api.h
  include/cpr/async.h
Labels: Feature :sparkles:
